'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
const apiUrl=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';

export default function Cart(){
 const [cart,setCart]=useState(null);const [loading,setLoading]=useState(true);const [busyId,setBusyId]=useState(null);const [message,setMessage]=useState('');const [authenticated,setAuthenticated]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{const response=await fetch(`${apiUrl}/v1/cart`,{credentials:'include',cache:'no-store'});const body=await response.json().catch(()=>null);if(response.status===401){setAuthenticated(false);setCart(null);return}if(!response.ok)throw new Error(body?.error?.message||'Unable to load your cart.');setAuthenticated(true);setCart(body.data)}catch(error){setMessage(error.message||'Unable to load your cart.')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 async function changeQuantity(item,delta){setBusyId(item.id);setMessage('');try{const response=await fetch(`${apiUrl}/v1/cart/items/${item.id}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:Math.max(0,item.quantity+delta)})});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message||'Unable to update your cart.');setCart(body.data);window.dispatchEvent(new Event('tadka:cart-updated'))}catch(error){setMessage(error.message||'Unable to update your cart.')}finally{setBusyId(null)}}
 return <main className="ref-page"><section className="ref-wrap ref-section"><div className="ref-head"><div><div className="ref-greeting">YOUR ORDER</div><h1>Cart</h1><p className="muted">Review your favourites before checkout.</p></div><Link href="/restaurants">Add more food →</Link></div>{!authenticated?<div className="card empty-state"><h3>Login to see your cart.</h3><Link className="ref-primary" href="/auth">Login</Link></div>:loading?<div className="card">Loading your cart…</div>:message&&!cart?.items?.length?<div className="card empty-state"><h3>We couldn't load your cart.</h3><p>{message}</p><button className="ref-primary" onClick={load}>Try again</button></div>:!cart?.items?.length?<div className="card empty-state"><h3>Your cart is empty.</h3><p>Find a kitchen and add something delicious.</p><Link className="ref-primary" href="/restaurants">Explore restaurants</Link></div>:<div className="ref-cart-layout"><section>{cart.items.map(item=><div className="ref-cart-row" key={item.id}><div><div className="ref-greeting">TADKA KITCHEN</div><b>{item.name}</b><div className="muted" style={{fontSize:12,marginTop:4}}>₹{item.price} each</div></div><div className="ref-qty"><button disabled={busyId===item.id} onClick={()=>changeQuantity(item,-1)}>−</button><b>{item.quantity}</b><button disabled={busyId===item.id} onClick={()=>changeQuantity(item,1)}>+</button></div></div>)}{message&&<div className="notice">{message}</div>}</section><aside className="ref-summary"><div className="ref-greeting">ORDER SUMMARY</div><h2>Your total</h2><div className="ref-summary-row"><span>Subtotal</span><b>₹{cart.subtotal}</b></div><div className="ref-summary-row"><span>Delivery</span><b>₹{cart.deliveryFee}</b></div><div className="ref-summary-row"><span>Taxes & charges</span><b>Included</b></div><div className="ref-summary-row ref-summary-total"><span>Total</span><b>₹{cart.total}</b></div><Link className="ref-primary" href="/checkout">Continue to checkout →</Link></aside></div>}</section></main>;
}
