'use client';
import {useEffect,useState} from 'react';
import RestaurantShell from '@/components/RestaurantShell'; import {supabase} from '@/lib/supabase';
const next={pending:'confirmed',confirmed:'preparing',preparing:'ready',ready:'picked_up',picked_up:'on_the_way',on_the_way:'delivered'}; const pretty=s=>String(s||'').replaceAll('_',' ');
export default function Orders(){const [orders,setOrders]=useState([]),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setMsg('Login required');setLoading(false);return}const r=await supabase.from('restaurants').select('id').eq('owner_id',user.id).maybeSingle();if(!r.data){setMsg('Restaurant owner access required.');setLoading(false);return}const q=await supabase.from('orders').select('id,status,subtotal,delivery_fee,created_at,order_items(id,name,quantity,price)').eq('restaurant_id',r.data.id).order('created_at',{ascending:false});if(q.error)setMsg(q.error.message);setOrders(q.data||[]);setLoading(false)} useEffect(()=>{load()},[]);
 async function advance(o){const n=next[o.status];if(!n)return;const {error}=await supabase.rpc('advance_order_status',{p_order_id:o.id,p_next_status:n});if(error)setMsg(error.message);else setOrders(xs=>xs.map(x=>x.id===o.id?{...x,status:n}:x))}
 const rows=filter==='all'?orders:orders.filter(o=>o.status===filter);
 return <RestaurantShell title="LIVE ORDER OPERATIONS" subtitle="Live Orders & Kitchen Queue"><div className="orders-page-toolbar"><div><b>{orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length} active orders</b><span> • Live kitchen queue</span></div><button className="partner-btn secondary" onClick={load}><span className="material-symbols-outlined">refresh</span> Refresh</button></div><div className="order-tabs">{['all','pending','confirmed','preparing','ready','picked_up','on_the_way','delivered'].map(s=><button key={s} className={filter===s?'active':''} onClick={()=>setFilter(s)}>{s==='all'?'All':pretty(s)} <b>{s==='all'?orders.length:orders.filter(o=>o.status===s).length}</b></button>)}</div>{msg&&<div className="partner-alert">{msg}<button onClick={()=>setMsg('')}>×</button></div>}{loading?<div className="partner-panel">Loading orders…</div>:<div className="kitchen-grid">{rows.map(o=><article className="kitchen-card" key={o.id}><div className="kitchen-card-top"><span className="order-id">#{o.id.slice(0,8).toUpperCase()}</span><span className={'status '+o.status}>{pretty(o.status)}</span></div><small>{new Date(o.created_at).toLocaleString()}</small><div className="kitchen-items">{(o.order_items||[]).map(i=><div key={i.id}><span>{i.name} × {i.quantity}</span><b>₹{Number(i.price*i.quantity).toFixed(0)}</b></div>)}</div><div className="kitchen-total"><b>₹{(Number(o.subtotal||0)+Number(o.delivery_fee||0)).toFixed(0)}</b>{next[o.status]?<button className="status-action" onClick={()=>advance(o)}>Mark {pretty(next[o.status])}</button>:<span className="done-mark"><span className="material-symbols-outlined">check_circle</span> Complete</span>}</div></article>)}{!rows.length&&<div className="partner-panel partner-empty compact"><span className="material-symbols-outlined">inbox</span><b>No orders in this queue</b><p>Try another status filter.</p></div>}</div>}</RestaurantShell>}
