'use client';
import { useEffect, useMemo, useState } from 'react';
import RestaurantShell from '@/components/RestaurantShell';
const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
async function api(path) { const r = await fetch(`${apiUrl}${path}`, { credentials: 'include', cache: 'no-store' }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(b?.error?.message || 'Request failed.'); return b?.data; }
export default function Analytics() {
 const [orders,setOrders]=useState([]),[msg,setMsg]=useState('');
 useEffect(()=>{api('/v1/restaurant/orders').then(setOrders).catch(e=>setMsg(e.message));},[]);
 const delivered=orders.filter(o=>o.status==='delivered'); const revenue=delivered.reduce((s,o)=>s+Number(o.total||0),0); const avg=delivered.length?revenue/delivered.length:0;
 const byStatus=useMemo(()=>Object.entries(orders.reduce((m,o)=>({...m,[o.status]:(m[o.status]||0)+1}),{})).sort((a,b)=>b[1]-a[1]),[orders]);
 return <RestaurantShell title="ANALYTICS & REVENUE" subtitle="Analytics & Revenue Intelligence">{msg&&<div className="partner-alert">{msg}</div>}<div className="partner-metrics"><Metric title="Gross Delivered" value={`₹${revenue.toFixed(0)}`} icon="payments"/><Metric title="Delivered Orders" value={delivered.length} icon="task_alt"/><Metric title="Average Order" value={`₹${avg.toFixed(0)}`} icon="shopping_bag"/><Metric title="All Orders" value={orders.length} icon="receipt_long"/></div><div className="partner-two-col"><section className="partner-panel"><div className="panel-head"><div><h2>Order Throughput</h2><p>Current order distribution from the restaurant API.</p></div></div><div className="category-list">{byStatus.map(([status,count])=><div className="category-row" key={status}><span className="material-symbols-outlined">receipt_long</span><b>{status.replaceAll('_',' ')}</b><span className="category-type">{count}</span></div>)}{!byStatus.length&&<div className="partner-empty compact">No order data yet.</div>}</div></section><section className="partner-panel"><div className="panel-head"><div><h2>Revenue Snapshot</h2><p>Only delivered orders are counted as completed revenue.</p></div></div><div className="category-list"><div className="category-row"><b>Delivered revenue</b><strong>₹{revenue.toFixed(0)}</strong></div><div className="category-row"><b>Average delivered order</b><strong>₹{avg.toFixed(0)}</strong></div></div></section></div></RestaurantShell>;
}
function Metric({title,value,icon}){return <div className="metric"><span className="metric-icon material-symbols-outlined">{icon}</span><small>{title}</small><strong>{value}</strong><span>Live restaurant API data</span></div>}
