'use client';

import Link from 'next/link';
import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';

const fallbackImage='https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80';
const apiUrl=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';

function MenuContent(){
 const params=useSearchParams(); const restaurantId=params.get('restaurant'); const [items,setItems]=useState([]); const [categories,setCategories]=useState([]); const [restaurant,setRestaurant]=useState(null); const [activeCategory,setActiveCategory]=useState('all'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true); const [addingId,setAddingId]=useState(null);
 useEffect(()=>{if(!restaurantId){setLoading(false);return undefined} const controller=new AbortController(); async function load(){setLoading(true);setMessage('');try{const response=await fetch(`${apiUrl}/v1/restaurants/${restaurantId}/menu`,{signal:controller.signal,cache:'no-store'});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message||'Unable to load this menu.');setRestaurant(body.data.restaurant);setItems(body.data.items||[]);setCategories(body.data.categories||[])}catch(error){if(error.name!=='AbortError')setMessage(error.message||'Unable to load this menu.')}finally{if(!controller.signal.aborted)setLoading(false)}}void load();return()=>controller.abort()},[restaurantId]);
 async function addToCart(itemId){setAddingId(itemId);setMessage('');try{const response=await fetch(`${apiUrl}/v1/cart/items`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({menuItemId:itemId,quantity:1})});const body=await response.json().catch(()=>null);if(response.status===401){setMessage('Login to add dishes to your cart.');return}if(!response.ok)throw new Error(body?.error?.message||'Unable to add this dish.');window.dispatchEvent(new Event('tadka:cart-updated'));setMessage('Added to cart.')}catch(error){setMessage(error.message||'Unable to add this dish.')}finally{setAddingId(null)}}
 const visible=activeCategory==='all'?items:items.filter(item=>item.categoryId===activeCategory);
 return <main className="ref-page"><section className="ref-menu-hero"><div className="ref-wrap"><div className="ref-greeting">{restaurant?.cuisine||'TADKA KITCHEN'}</div><h1>{restaurant?.name||'Restaurant menu'}</h1><p className="muted">{restaurant?.description||'Fresh Indian favourites prepared to order.'}</p><div className="ref-meta"><span className="ref-rating">★ {restaurant?.rating||'New'}</span><span>25–35 min</span><span>₹{restaurant?.deliveryFee||0} delivery</span></div></div></section><section className="ref-wrap ref-section"><div className="ref-menu-grid"><div><div className="ref-cats" style={{marginBottom:18}}><button className={`ref-cat ${activeCategory==='all'?'active':''}`} onClick={()=>setActiveCategory('all')}>Recommended</button>{categories.map(category=><button className={`ref-cat ${activeCategory===category.id?'active':''}`} key={category.id} onClick={()=>setActiveCategory(category.id)}>{category.name}</button>)}</div>{message&&<div className="notice">{message}</div>}{loading?<div className="card">Loading menu…</div>:visible.length===0?<div className="card empty-state"><h3>No dishes here yet.</h3><p className="muted">Try another category.</p></div>:<div className="ref-menu-list">{visible.map(item=><article className="ref-menu-item" key={item.id}><div><div className="ref-greeting">CHEF'S PICK</div><h3>{item.name}</h3><p>{item.description||'Freshly prepared and delivered with care.'}</p><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><span className="ref-price">₹{Number(item.price).toFixed(0)}</span><button className="ref-add" disabled={addingId===item.id} onClick={()=>addToCart(item.id)}>{addingId===item.id?'ADDING…':'+ ADD'}</button></div></div><img src={item.imageUrl||fallbackImage} alt=""/></article>)}</div>}</div><aside className="ref-cart-card"><div className="ref-greeting">YOUR ORDER</div><h3>Ready to eat?</h3><p>Add your favourites from this kitchen. Your live cart stays connected to checkout.</p><Link className="ref-primary" href="/cart">View cart →</Link></aside></div></section></main>;
}
export default function Menu(){return <Suspense fallback={<main className="ref-page"><section className="ref-wrap ref-section"><div className="card">Loading menu…</div></section></main>}><MenuContent/></Suspense>}
