'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import './account.css';
const apiUrl=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';
const roleLabels={customer:'Customer',restaurant_staff:'Restaurant Staff',rider:'Delivery Partner',admin:'Admin'};
const statusCopy={pending:'Order received',confirmed:'Kitchen confirmed',preparing:'Preparing',ready:'Ready for pickup',picked_up:'Out for delivery',delivered:'Delivered',cancelled:'Cancelled'};
const roleDashboard={restaurant_staff:'/restaurant',rider:'/delivery',admin:'/admin'};
export default function AccountPage(){
 const [user,setUser]=useState(null),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;Promise.all([fetch(`${apiUrl}/v1/auth/me`,{credentials:'include',cache:'no-store'}),fetch(`${apiUrl}/v1/orders`,{credentials:'include',cache:'no-store'})]).then(async([ur,or])=>{const ub=await ur.json().catch(()=>null),ob=await or.json().catch(()=>null);if(!ur.ok)throw new Error(ub?.error?.message||'Please sign in to continue.');if(active){setUser(ub.data?.user||ub.data||null);setOrders(or.ok?ob?.data||[]:[])}}).catch(e=>{if(active)setMessage(e.message||'Unable to load your account.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function logout(){const r=await fetch(`${apiUrl}/v1/auth/logout`,{method:'POST',credentials:'include'});if(!r.ok)return setMessage('Unable to sign out. Please try again.');window.location.href='/'}
 if(loading)return <main className="accountPage"><div className="accountLoading">Loading your account…</div></main>;
 if(!user)return <main className="accountPage"><div className="accountSignedOut"><span className="accountKicker">TADKA ACCOUNT</span><h1>Your food journey starts here.</h1><p>Please sign in to manage your profile and orders.</p><Link className="accountPrimary" href="/auth">Sign in / Create account</Link></div></main>;
 const role=roleLabels[user.role]||user.role||'Customer',activeOrder=orders.find(o=>!['delivered','cancelled'].includes(o.status)),completed=orders.filter(o=>o.status==='delivered').length,initials=(user.fullName||user.email||'U').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(),dashboard=roleDashboard[user.role],recentOrders=orders.slice(0,3);
 return <main className="accountPage"><div className="accountShell">
  <aside className="accountSidebar"><Link href="/" className="accountBrand"><img src="/tadka-logo.svg" alt="Tadka" /></Link><div className="accountUserCard"><div className="accountAvatar">{initials}</div><strong>{user.fullName||'Tadka customer'}</strong><span>{user.email}</span><b>{role}</b></div><nav className="accountSideNav"><Link className="active" href="/account"><span className="material-symbols-outlined">dashboard</span>Dashboard</Link><Link href="/account/profile"><span className="material-symbols-outlined">person</span>Profile</Link><Link href="/orders"><span className="material-symbols-outlined">receipt_long</span>My Orders</Link><Link href="/restaurants"><span className="material-symbols-outlined">favorite</span>Saved Restaurants</Link><Link href="/cart"><span className="material-symbols-outlined">shopping_bag</span>Bag</Link>{dashboard&&<Link href={dashboard}><span className="material-symbols-outlined">space_dashboard</span>{role} Dashboard</Link>}</nav><div className="accountSideMessage"><span className="material-symbols-outlined">restaurant</span><span>Good Food<br/><strong>Brings Happiness!</strong></span></div><button className="accountSideSignout" onClick={logout}>Sign out</button></aside>
  <section className="accountMain"><div className="accountWelcome"><div><span className="accountKicker">WELCOME BACK</span><h1>Hi, {user.fullName||'there'}!</h1><p>Craving something delicious? Let’s find your next meal.</p></div><div className="accountFoodArt"><span>Good Food<br/>Brings Us<br/>Together.</span><img src="https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=700&q=85" alt="Indian biryani"/></div></div>
   <div className="accountStats"><article><span className="statIcon orange material-symbols-outlined">shopping_bag</span><div><small>Total Orders</small><strong>{orders.length}</strong><span>Your food journey</span></div></article><article><span className="statIcon green material-symbols-outlined">check_circle</span><div><small>Completed</small><strong>{completed}</strong><span>Meals enjoyed</span></div></article><article><span className="statIcon gold material-symbols-outlined">schedule</span><div><small>Active Order</small><strong>{activeOrder?'1':'0'}</strong><span>On the way</span></div></article><article><span className="statIcon red material-symbols-outlined">verified_user</span><div><small>Account</small><strong>{role}</strong><span>Access level</span></div></article></div>
   {activeOrder&&<section className="accountActive"><div><span className="accountKicker">ACTIVE ORDER</span><h2>{activeOrder.restaurantName||'Your Tadka order'}</h2><p>{statusCopy[activeOrder.status]||activeOrder.status} · ₹{activeOrder.total}</p></div><Link href={`/orders/${activeOrder.id}`} className="accountPrimary">Track order →</Link></section>}
   <section className="accountPanel"><div className="accountPanelHead"><div><h2>Quick Actions</h2><p>Everything you need, right here</p></div></div><div className="quickGrid"><Link href="/restaurants"><span className="quickIcon orange material-symbols-outlined">restaurant</span><strong>Order Food</strong><small>Find amazing restaurants</small><b>→</b></Link><Link href="/orders"><span className="quickIcon green material-symbols-outlined">receipt_long</span><strong>My Orders</strong><small>Track & reorder</small><b>→</b></Link><Link href="/restaurants"><span className="quickIcon red material-symbols-outlined">favorite</span><strong>Saved Places</strong><small>Explore favourites</small><b>→</b></Link><Link href="/account/profile"><span className="quickIcon gold material-symbols-outlined">person</span><strong>My Profile</strong><small>Manage your account</small><b>→</b></Link></div></section>
   <section className="accountPanel"><div className="accountPanelHead"><div><h2>Recent Orders</h2><p>Your latest Tadka orders</p></div><Link href="/orders">View All →</Link></div>{recentOrders.length?<div className="recentOrders">{recentOrders.map(o=><Link href={`/orders/${o.id}`} key={o.id}><span className="recentOrderIcon material-symbols-outlined">receipt_long</span><div><strong>{o.restaurantName||'Tadka restaurant'}</strong><small>{statusCopy[o.status]||o.status}</small></div><b>₹{o.total}</b><span>→</span></Link>)}</div>:<div className="accountEmpty"><span className="emptyIcon material-symbols-outlined">shopping_bag</span><div><strong>No orders yet</strong><p>When you place an order, it will appear here.</p></div><Link className="accountPrimary" href="/restaurants">Start Ordering</Link></div>}</section>
  </section>
  <aside className="accountRightRail"><section className="railCard"><div className="railHead"><h2>Your Profile</h2><Link href="/account/profile">Edit</Link></div><div className="railLine"><span className="material-symbols-outlined">person</span>{user.fullName||'Not provided'}</div><div className="railLine"><span className="material-symbols-outlined">mail</span>{user.email}</div><div className="railLine"><span className="material-symbols-outlined">shield</span>{role}</div></section><section className="railPromo"><div><span className="accountKicker">DISCOVER</span><h2>Amazing food<br/>is waiting.</h2><p>Explore restaurants and find your next meal.</p><Link href="/restaurants" className="accountPrimary">Explore Now →</Link></div><img src="https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=85" alt="Indian paneer dish"/></section></aside>
 </div></main>;
}