'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import './account.css';
const apiUrl=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';
const roleLabels={customer:'Customer',restaurant_staff:'Restaurant Staff',rider:'Delivery Partner',admin:'Admin'};
const statusCopy={pending:'Order received',confirmed:'Kitchen confirmed',preparing:'Preparing',ready:'Ready for pickup',picked_up:'Out for delivery',delivered:'Delivered',cancelled:'Cancelled'};
export default function AccountPage(){
 const [user,setUser]=useState(null),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;Promise.all([fetch(`${apiUrl}/v1/auth/me`,{credentials:'include',cache:'no-store'}),fetch(`${apiUrl}/v1/orders`,{credentials:'include',cache:'no-store'})]).then(async([ur,or])=>{const ub=await ur.json().catch(()=>null),ob=await or.json().catch(()=>null);if(!ur.ok)return;if(active){setUser(ub.data?.user||ub.data||null);setOrders(or.ok?ob?.data||[]:[])}}).catch(()=>{if(active)setMessage('Unable to load your account.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function logout(){setMessage('');const r=await fetch(`${apiUrl}/v1/auth/logout`,{method:'POST',credentials:'include'});if(!r.ok)return setMessage('Unable to sign out. Please try again.');window.location.href='/'}
 if(loading)return <main className="accountPage"><div className="accountInner"><section className="panel"><p>Loading your account…</p></section></div></main>;
 if(!user)return <main className="accountPage"><div className="accountInner"><section className="panel"><h1>Your account</h1><p>Please sign in to continue.</p><Link className="btn primary" href="/auth">Sign in</Link></section></div></main>;
 const role=roleLabels[user.role]||user.role||'Customer',activeOrder=orders.find(o=>!['delivered','cancelled'].includes(o.status)),completed=orders.filter(o=>o.status==='delivered').length;
 return <main className="accountPage"><div className="accountInner"><header className="accountHeader"><span className="eyebrow">ACCOUNT</span><h1>Welcome{user.fullName?`, ${user.fullName}`:''}.</h1><p className="accountEmail">{user.email}</p></header>
 <section className="accountOverview"><div><span>ACCOUNT ROLE</span><strong>{role}</strong></div><div><span>ORDERS</span><strong>{orders.length}</strong></div><div><span>COMPLETED</span><strong>{completed}</strong></div><div><span>ACTIVE</span><strong>{activeOrder?'1':'0'}</strong></div></section>
 {activeOrder&&<section className="accountActiveOrder"><div><span className="eyebrow">ACTIVE ORDER</span><h2>{activeOrder.restaurantName}</h2><p>{statusCopy[activeOrder.status]||activeOrder.status} • ₹{activeOrder.total}</p></div><Link className="btn primary" href={`/orders/${activeOrder.id}`}>Track order</Link></section>}
 <section className="accountCards" aria-label="Account options">
 <Link className="accountCard" href="/account/profile"><span className="accountIcon material-symbols-outlined">person</span><span className="accountCardInfo"><strong className="accountCardTitle">Profile</strong><span className="accountCardText">Manage your name and account details</span></span><span className="accountArrow">→</span></Link>
 <Link className="accountCard" href="/orders"><span className="accountIcon material-symbols-outlined">receipt_long</span><span className="accountCardInfo"><strong className="accountCardTitle">Your Orders</strong><span className="accountCardText">Track current orders and view your complete history</span></span><span className="accountArrow">→</span></Link>
 <Link className="accountCard" href="/restaurants"><span className="accountIcon material-symbols-outlined">restaurant</span><span className="accountCardInfo"><strong className="accountCardTitle">Discover Food</strong><span className="accountCardText">Explore restaurants and find your next meal</span></span><span className="accountArrow">→</span></Link>
 {user.role==='restaurant_staff'&&<Link className="accountCard" href="/restaurant"><span className="accountIcon material-symbols-outlined">storefront</span><span className="accountCardInfo"><strong className="accountCardTitle">Restaurant Dashboard</strong><span className="accountCardText">Manage your restaurant, menu and incoming orders</span></span><span className="accountArrow">→</span></Link>}
 {user.role==='rider'&&<Link className="accountCard" href="/delivery"><span className="accountIcon material-symbols-outlined">two_wheeler</span><span className="accountCardInfo"><strong className="accountCardTitle">Delivery Dashboard</strong><span className="accountCardText">View assigned deliveries and update delivery status</span></span><span className="accountArrow">→</span></Link>}
 {user.role==='admin'&&<Link className="accountCard" href="/admin"><span className="accountIcon material-symbols-outlined">admin_panel_settings</span><span className="accountCardInfo"><strong className="accountCardTitle">Admin Dashboard</strong><span className="accountCardText">Manage users, restaurants, orders and platform operations</span></span><span className="accountArrow">→</span></Link>}
 </section><div className="accountActions"><Link className="accountHomeLink" href="/">← Back to Tadka</Link><button className="signOutButton" onClick={logout}>Sign out</button></div>{message&&<p className="accountMessage">{message}</p>}</div></main>;
}
