'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
async function api(path, options = {}) { const response = await fetch(`${apiUrl}${path}`, { ...options, credentials: 'include', cache: 'no-store', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error?.message || 'Request failed.'); return body?.data; }

export default function AdminDelivery() {
  const [riders, setRiders] = useState([]); const [deliveries, setDeliveries] = useState([]); const [orders, setOrders] = useState([]); const [riderByOrder, setRiderByOrder] = useState({}); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  async function load() { setLoading(true); try { const [r, d, o] = await Promise.all([api('/v1/admin/riders'), api('/v1/admin/deliveries'), api('/v1/admin/orders')]); setRiders(r || []); setDeliveries(d || []); setOrders((o || []).filter((x) => ['confirmed', 'preparing', 'ready'].includes(x.status))); setMessage(''); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function assign(orderId) { const riderId = riderByOrder[orderId]; if (!riderId) return; try { await api('/v1/admin/deliveries', { method: 'POST', body: JSON.stringify({ orderId, riderId }) }); setRiderByOrder((current) => ({ ...current, [orderId]: '' })); await load(); } catch (error) { setMessage(error.message); } }
  return <main className="mx-auto w-full max-w-6xl px-4 py-10"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-tadka-orange">ADMIN</span><h1>Delivery Control</h1><p>Assign active orders to riders and monitor delivery progress.</p></div><button className="rounded-xl border border-tadka-line bg-white px-4 py-2.5 text-sm font-bold" onClick={load}>Refresh</button></div>{message && <div className="my-3 rounded-xl border border-orange-200 bg-orange-50 p-3 text-sm text-tadka-danger">{message}<button onClick={() => setMessage('')}>×</button></div>}
    {loading ? <section className="rounded-2xl border border-tadka-line bg-white p-6 shadow-tadka-sm"><p>Loading delivery operations…</p></section> : <><section className="rounded-2xl border border-tadka-line bg-white p-6 shadow-tadka-sm"><div className="mb-4 flex items-start justify-between gap-4"><div><h2>Assign orders</h2><p>Only confirmed, preparing, and ready orders can be assigned.</p></div></div>{!orders.length ? <p className="text-sm text-tadka-muted">No active orders need assignment.</p> : <div className="grid gap-3">{orders.map((order) => <article className="flex flex-col justify-between gap-4 rounded-2xl border border-tadka-line p-4 sm:flex-row sm:items-center" key={order.id}><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-tadka-orange">{order.status.replace('_', ' ').toUpperCase()}</span><h3>Order #{order.id.slice(0, 8)}</h3><p>₹{order.total}</p></div><div className="flex flex-col gap-2 sm:flex-row"><select value={riderByOrder[order.id] || ''} onChange={(e) => setRiderByOrder((current) => ({ ...current, [order.id]: e.target.value }))}><option value="">Select rider</option>{riders.map((rider) => <option key={rider.id} value={rider.id}>{rider.fullName || rider.email}</option>)}</select><button className="rounded-xl bg-tadka-orange px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50" disabled={!riderByOrder[order.id]} onClick={() => assign(order.id)}>Assign</button></div></article>)}</div>}</section>
    <section className="rounded-2xl border border-tadka-line bg-white p-6 shadow-tadka-sm"><div className="mb-4 flex items-start justify-between gap-4"><div><h2>Delivery activity</h2><p>{deliveries.length} delivery record{deliveries.length === 1 ? '' : 's'}</p></div></div>{!deliveries.length ? <p className="text-sm text-tadka-muted">No deliveries assigned yet.</p> : <div className="grid gap-3">{deliveries.map((delivery) => <article className="flex flex-col justify-between gap-4 rounded-2xl border border-tadka-line p-4 sm:flex-row sm:items-center" key={delivery.id}><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-tadka-orange">{delivery.status.replace('_', ' ').toUpperCase()}</span><h3>Order #{delivery.orderId.slice(0, 8)}</h3><p>{delivery.restaurantName} · {delivery.riderName || 'Rider'}</p><p className="text-sm text-tadka-muted">{delivery.address}</p></div><strong>₹{delivery.total}</strong></article>)}</div>}</section></>}
    <Link className="rounded-xl border border-tadka-line bg-white px-4 py-2.5 text-sm font-bold" href="/admin">Back to admin</Link></main>;
}
