'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
const statusCopy = { pending: 'Order received', confirmed: 'Kitchen confirmed', preparing: 'Being prepared', ready: 'Ready for pickup', picked_up: 'Picked up', delivered: 'Delivered', cancelled: 'Cancelled' };

export default function OrdersPage() {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [reviewing, setReviewing] = useState(null); const [rating, setRating] = useState(5); const [comment, setComment] = useState('');
  async function load() { try { const response = await fetch(`${apiUrl}/v1/orders`, { credentials: 'include', cache: 'no-store' }); const body = await response.json(); if (response.status === 401) { setMessage('Login to view your orders.'); return; } if (!response.ok) throw new Error(body?.error?.message || 'Unable to load orders.'); setOrders(body.data || []); setMessage(''); } catch (error) { setMessage(error.message || 'Unable to load orders.'); } finally { setLoading(false); } }
  useEffect(() => { load(); const timer = setInterval(load, 15000); return () => clearInterval(timer); }, []);
  async function submitReview(event) { event.preventDefault(); try { const response = await fetch(`${apiUrl}/v1/orders/${reviewing}/review`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rating, comment: comment.trim() || null }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to submit review.'); setReviewing(null); setComment(''); setRating(5); setMessage('Thanks — your review was submitted.'); } catch (error) { setMessage(error.message); } }
  if (loading) return <main className="mx-auto w-full max-w-[1200px] px-4 py-9 pb-20"><div className="rounded-2xl border border-tadka-line bg-white p-6 shadow-tadka-sm">Loading your orders…</div></main>;
  if (message && !orders.length) return <main className="mx-auto w-full max-w-3xl px-4 py-12 text-center"><div className="rounded-2xl border border-tadka-line bg-white p-8 text-center shadow-tadka-sm"><h2>{message}</h2><Link className="inline-flex items-center justify-center rounded-xl bg-tadka-orange px-4 py-3 text-sm font-bold text-white" href="/auth">Login</Link></div></main>;
  return <main className="mx-auto w-full max-w-[1200px] px-4 py-9 pb-20"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-tadka-orange">ORDER HISTORY</span><h1>Your orders.</h1><p>Track every order from kitchen confirmation to doorstep.</p></div><Link className="inline-flex items-center justify-center rounded-xl bg-tadka-orange px-4 py-3 text-sm font-bold text-white" href="/restaurants">Order food</Link></div>{message && <div className="my-3 rounded-xl border border-orange-200 bg-orange-50 p-3 text-sm text-tadka-danger">{message}</div>}
    {!orders.length && <section className="rounded-2xl border border-tadka-line bg-white p-8 text-center shadow-tadka-sm"><h2>No orders yet</h2><p>Completed checkouts will appear here.</p><Link className="inline-flex items-center justify-center rounded-xl bg-tadka-orange px-4 py-3 text-sm font-bold text-white" href="/restaurants">Explore restaurants</Link></section>}
    <div className="grid gap-4">{orders.map((order) => <article className="rounded-2xl border border-tadka-line bg-white p-6 shadow-tadka-sm" key={order.id}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-tadka-orange">#{order.id.slice(0, 8).toUpperCase()}</span><h2 style={{ margin: '5px 0' }}>{order.restaurantName}</h2><p className="text-sm text-tadka-muted" style={{ fontSize: 12 }}>{new Date(order.createdAt).toLocaleString()}</p></div><div style={{ textAlign: 'right' }}><span className="inline-flex rounded-full bg-tadka-bg px-3 py-1.5 text-xs font-bold">{statusCopy[order.status] || order.status}</span><strong style={{ display: 'block', fontSize: 20, marginTop: 7 }}>₹{order.total}</strong></div></div><div className="my-4 grid gap-2 text-sm">{order.items.map((item) => <div key={item.id}><span>{item.quantity} × {item.name}</span><b>₹{item.lineTotal}</b></div>)}</div><div className="flex justify-between gap-3 border-t border-tadka-line py-2 text-sm"><span>Payment</span><b>{order.paymentMethod === 'cod' ? 'Cash on Delivery' : `Online · ${order.paymentStatus}`}</b></div><div className="mt-4 flex flex-wrap gap-2"><Link className="rounded-xl border border-tadka-line bg-white px-4 py-2.5 text-sm font-bold" href={`/orders/${order.id}`}>{'View order'}</Link>{order.status === 'delivered' && <button className="rounded-xl bg-tadka-orange px-4 py-2.5 text-sm font-bold text-white" onClick={() => setReviewing(order.id)}>Rate restaurant</button>}</div></article>)}</div>
    {reviewing && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" role="dialog" aria-modal="true"><form className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-tadka-lg" onSubmit={submitReview}><h2>Rate your order</h2><p>How was your experience?</p><div className="flex gap-2 py-4">{[1,2,3,4,5].map((value) => <button type="button" key={value} aria-label={`${value} stars`} onClick={() => setRating(value)}>{value <= rating ? '★' : '☆'}</button>)}</div><textarea maxLength={1000} placeholder="Tell us what you liked…" value={comment} onChange={(e) => setComment(e.target.value)} /><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="rounded-xl border border-tadka-line bg-white px-4 py-2.5 text-sm font-bold" onClick={() => setReviewing(null)}>Cancel</button><button className="rounded-xl bg-tadka-orange px-4 py-2.5 text-sm font-bold text-white">Submit review</button></div></form></div>}
  </main>;
}
